name: property_managment
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  webview_cookie_manager: ^2.0.6
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.0
  dropdown_button2: ^1.9.1
  universal_html: ^2.0.9
  get: ^4.6.5
  intl: ^0.17.0
  table_calendar: ^3.0.8
  webview_windows: ^0.1.6
  file_picker: ^5.2.2
  flutter_local_notifications: ^12.0.4
  http: ^0.13.5
  notification_permissions: ^0.6.1
  webview_flutter: ^3.0.1
  intl_phone_number_input: ^0.7.1
  country_picker: ^2.0.17
  audioplayers: ^2.0.0
  dotted_border: ^2.0.0+3
  get_storage: ^2.0.3
  video_player: ^2.4.10
  photo_view: ^0.14.0
  validators: ^3.0.0
  themed: ^4.0.0
  flutter_image_compress:
  mime:
  shared_preferences: ^2.0.15
  syncfusion_flutter_datepicker: ^20.3.59
  smooth_page_indicator: ^1.0.0+2
  timelines: ^0.1.0
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^7.3.0
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6
  percent_indicator: ^4.2.3
  device_info_plus: ^8.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  dots_indicator: ^2.1.0

  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/
    - assets/common/
    - assets/common/images/
    - assets/common/svg_icon/logo_svg.svg

    - assets/fonts/
  fonts:
    - family: TAJAWAL
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
  uses-material-design: true
